/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medical;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jbj
 */
public class bill extends javax.swing.JFrame {
DefaultTableModel model1=new DefaultTableModel();
String[] col_list={"Product","Company","Quantity","Amount"};
    Connection con;
    /**
     * Creates new form bill
     */
    public bill() {
         try {
             try {
                 initComponents();
                 setBounds(0,0,726,712);
                 this.getContentPane().setBackground(Color.white);
                 jTable2.setModel(model1);
                 try {
                     Class.forName("com.mysql.jdbc.Driver");
                     try {
                         con=DriverManager.getConnection("jdbc:mysql://localhost:3306/medical", "root", "");
                     } catch (SQLException ex) {
                         
                     }
                     
                 }
                 
                 catch (ClassNotFoundException ex) {
                     JOptionPane.showMessageDialog(rootPane,ex.toString());
                     
                 }
                 NewClass n2=new NewClass();
                 jLabel4.setText(n2.set_bill_no());
                 jLabel5.setText(n2.set_date());
                 jLabel11.setText(Long.toString(n2.set_total()));
                 model1.setColumnIdentifiers(col_list);
                 Statement st = con.createStatement();
                 try {
                     
                     String str="select product_name,brand,spp_quantity,s_price from bill_detail where bill_no='"+n2.set_bill_no()+"'";
                     //Statement st=con.createStatement();
                     ResultSet r =st.executeQuery(str);
                     while(r.next())
                     {
                         String str1=r.getString("product_name");
                         String str4=r.getString("brand");
                         Long str2=r.getLong("spp_quantity");
                         Long str3=r.getLong("s_price")*(str2);
                         //JOptionPane.showMessageDialog(rootPane,"s="+str3);
                         Object[] obj={str1,str4,str2,str3};
                         model1.addRow(obj);
                     }
                     
                 } catch (SQLException ex) {
                     Logger.getLogger(sales_bill1.class.getName()).log(Level.SEVERE, null, ex);
                 }
                 
                 ResultSet rs = st.executeQuery("select pic from image");
                 if(rs.next()){
                     try {
                         byte[] img = rs.getBytes("pic");
                         
                         
                         
                         //Resize The ImageIcon
                         ImageIcon image = new ImageIcon(img);
                         Image im = image.getImage();
                         Image myImg = im.getScaledInstance(jLabel7.getWidth(), jLabel7.getHeight(),Image.SCALE_SMOOTH);
                         ImageIcon newImage = new ImageIcon(myImg);
                         jLabel7.setIcon(newImage);
                     } catch (SQLException ex) {
                         Logger.getLogger(bill.class.getName()).log(Level.SEVERE, null, ex);
                     }
                 }
                 
             }
             
             catch (SQLException ex) {
                 Logger.getLogger(bill.class.getName()).log(Level.SEVERE, null,ex);
                 
             }
             String q="select address, shop from login";
             Statement st1=con.createStatement();
             ResultSet r =st1.executeQuery(q);
             r.next();
             jLabel9.setText(r.getString("shop"));
             jLabel1.setText(r.getString("address"));
                 
             }
             
             catch (SQLException ex) {
                 Logger.getLogger(bill.class.getName()).log(Level.SEVERE, null,ex);
                 
             }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable()
        {
            public boolean isCellEditable(int row,int col)
            {
                return false;
            }
        }
        ;
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Print");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(210, 670, 270, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Rs.");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(380, 620, 70, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("-");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(460, 620, 160, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("TOTAL");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(110, 620, 80, 20);

        jTable2.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Quantity", "Amount"
            }
        ));
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 240, 670, 370);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Bill No. :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 210, 130, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("-");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(170, 210, 140, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Date:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(440, 210, 120, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("-");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(570, 210, 150, 20);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel9.setText("jLabel9");
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(240, 0, 480, 100);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setText("ADDRESS:");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(240, 100, 470, 90);

        jLabel7.setBackground(new java.awt.Color(250, 250, 41));
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 0, 220, 190);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("AMOUNT:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(190, 620, 90, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 730, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
        PrinterJob job=PrinterJob.getPrinterJob();
    job.setJobName("printdata");
    job.setPrintable(new Printable() {
        @Override
        public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
            if(pageIndex>0)
            {
               return Printable.NO_SUCH_PAGE; 
            }
                
 
        Graphics2D g2d = (Graphics2D)graphics;
        g2d.translate(pageFormat.getImageableX()+15, pageFormat.getImageableY()+15);
        g2d.scale( 0.75, 0.75);
               
        jPanel1.print(g2d);
 
        return Printable.PAGE_EXISTS;
    

            //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    });
    boolean ok=job.printDialog();
    if(ok)
    {
        try {
            job.print();
            this.dispose();
        } catch (PrinterException ex) {
            Logger.getLogger(bill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    else
    { /*try {
         String bill_no=jLabel4.getText();
         //JOptionPane.showMessageDialog(rootPane,bill_no);
            String s="delete from bill_detail where bill_no='"+bill_no+"'";
            String s1="delete from bill where bill_no='"+bill_no+"'";
            Statement st=con.createStatement();
            st.executeUpdate(s);
           st.executeUpdate(s1);
             
            //String str="delete from bill_detail where bill_no="+st11+"";
            
            //st.executeUpdate(str);
           // this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(bill.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    this.dispose();
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
