/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medical;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jbj
 */
public class check_stock extends javax.swing.JInternalFrame {
DefaultTableModel model1=new DefaultTableModel();
Connection con;

    /**
     * Creates new form maintain_order
     */
    public check_stock() {
  
    try {
        initComponents();
        //setBounds(0,0,1365,680);
       /*JFrame f=new JFrame();
       f.setExtendedState(JFrame.MAXIMIZED_BOTH);
       f.setUndecorated(true);
       f.setResizable(true);*/
         ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        Dimension scn=Toolkit.getDefaultToolkit().getScreenSize();
        pack();
        setSize(scn.width,scn.height);
        jTable1.setModel(model1);
        jTable1.getTableHeader().setFont(new Font("Tahoma", Font.BOLD,18));
        //model1.setColumnIdentifiers(col_list);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            try {
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/medical", "root", "");
            } catch (SQLException ex) {
                
            }
            
        } 
        
        catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane,ex.toString());
            
        }
        String str1="select product_name,brand,stock_quantity from inventory  where stock_quantity<=min_level";
        Statement st1=con.createStatement();
        ResultSet rs=st1.executeQuery(str1);
       
        String[] col_list={"Product Name","Company","Stock Quantity"};
        model1.setColumnIdentifiers(col_list);
        
        while( rs.next())
        {
            
            String pname=rs.getString("product_name");
            String brand=rs.getString("brand");
            
            Long sq=rs.getLong("stock_quantity");
            Object[] obj={pname,brand,sq};
           model1.addRow(obj);
        }
        
        
        
        
        
        
        
    }
    
    catch (SQLException ex) {
        Logger.getLogger(check_stock.class.getName()).log(Level.SEVERE, null,ex);
        
    }
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable()
        {

            public boolean isCellEditable(int row,int col)
            {
                return false;
            }

        }

        ;
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("           TO ORDER");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(450, 10, 380, 44);

        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(620, 130, 680, 370);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Exit");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(840, 550, 210, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medical/images/Inventory-Medical-Case-Study1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 820, 740);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setText("X");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1330, 10, 20, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   this.dispose();    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private Object getjJTable() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
