/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medical;

import com.sun.java.swing.plaf.windows.resources.windows;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowEvent;
import java.sql.Connection;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Calendar;
import java.util.Date;
import javax.swing.table.TableModel;
import static medical.order.back;
import static medical.order.model1;


/**
 *
 * @author jbj
 */
public class order_internal extends javax.swing.JFrame {
 DefaultTableModel model1=new DefaultTableModel();
  Connection con;
 
    static  int count;    
       
   
    /**
     * Creates new form NewJFrame
     */
    public order_internal() {
      
 
    initComponents();
    //jPanel1.setBackground(Color.WHITE);
    jLabel4.setBackground(Color.WHITE);
    
     
    jTable1.getTableHeader().setFont(new Font("Tahoma", Font.BOLD,18));
  //  jLabel2.setVisible(false);
    jLabel3.setVisible(false);
  //  jLabel4.setVisible(false);
    jLabel5.setVisible(false);
    jButton1.setVisible(false);
    setBounds(0,0,1365, 700);
    jTable1.setModel(model1);
    
    //jTable1.setEnabled(false);
    
    try {
        Class.forName("com.mysql.jdbc.Driver");
        try {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/medical", "root", "");
        } catch (SQLException ex) {
            
        }
        
    }
    
    catch (ClassNotFoundException ex) {
        JOptionPane.showMessageDialog(rootPane,ex.toString());
        
    }
   
    String[] col_list={"Product name","Company","Quantity"};
    model1.setColumnIdentifiers(col_list);
    try
    {
         
        String str="select product_name,brand,o_quantity from order1_arbt";
        
        Statement st=con.createStatement();
        ResultSet re=st.executeQuery(str);
        
        while(re.next())
        {
            int col_count=col_list.length;
            Object[] new_row=new Object[col_count];
            for(int i=0;i<col_count;i++)
            {
                new_row[i]=re.getObject(i+1);
            }
            model1.addRow(new_row);
        }
        
        
    }
    catch(Exception ex)
    {
        JOptionPane.showMessageDialog(rootPane, ex.toString());
    }
   
    String sql="select suppliername from supplier";
    try
    {
        Statement st=con.createStatement();
        //jComboBox1.removeAllItems();
       
        ResultSet r=st.executeQuery(sql);
        while(r.next())
        {
            jComboBox1.addItem(r.getString("suppliername"));
            
        }
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(rootPane,e.toString());
    }
    Date date=new Date();
    DateFormat df=new SimpleDateFormat("dd/MM/yyyy");
    String fmd=df.format(date);
    jLabel8.setText(fmd);
    jTable1.setComponentPopupMenu(jPopupMenu1);
   
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable()
        {
            public boolean isCellEditable(int row,int col)

            {
                return false;
            }
        }
        ;
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jMenuItem1.setText("Delete");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Order No.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(650, 110, 90, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 204, 0));
        jLabel6.setText("                 CONFIRM ORDER");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(310, 20, 660, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(810, 110, 120, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Supplier Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(650, 160, 160, 20);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-SELECT-" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(810, 160, 280, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(810, 210, 130, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Supplier Id");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(650, 210, 130, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(690, 670, 230, 30);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(610, 280, 620, 230);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(680, 550, 210, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(960, 550, 220, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Date");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(970, 110, 90, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(1090, 110, 130, 20);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel9.setText("X");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(1310, 20, 20, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medical/images/Capture17.PNG"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 80, 630, 600);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1840, 1040);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
//public void close()
//{
//}
    int opt=1;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        if(jComboBox1.getSelectedItem()!="-SELECT-")
        {
          opt=  JOptionPane.showConfirmDialog(rootPane, "Do you want to save changes?", "Confirmation", JOptionPane.YES_NO_OPTION);
          if(opt==0)
          {
              jComboBox1.setEnabled(false);
              
          try {                                         
            try {
                jLabel2.setVisible(true);
                jLabel3.setVisible(true);
                jLabel4.setVisible(true);
                jLabel5.setVisible(true);
                try {
        int rows=jTable1.getRowCount();
        String str="insert into order1(product_name,o_quantity,brand) values(?,?,?)";
        PreparedStatement pst=con.prepareStatement(str);
        for(int row=0;row<rows;row++)
        {
        String p_name=(String) jTable1.getValueAt(row,0);
           long o_quant =(long) jTable1.getValueAt(row,2);
        String brand=(String) jTable1.getValueAt(row,1);
        
        pst.setString(1, p_name);
        pst.setLong(2, o_quant);
        pst.setString(3,brand);
        pst.addBatch();
            
        }
        pst.executeBatch();


    } catch (SQLException ex) {
        Logger.getLogger(order.class.getName()).log(Level.SEVERE, null, ex);
    }
    
   String str2="delete from order1_arbt";
         Statement st=con.createStatement();
                st.executeUpdate(str2);        
                
                
                
                String s_id="";
                try {
                    String str=(String) jComboBox1.getSelectedItem();
                    
                    String str1="select s_id from supplier where suppliername='"+str+"'";
                   // Statement st=con.createStatement();
                    ResultSet rs= st.executeQuery(str1);
                    rs.next();
                    s_id=rs.getString("s_id");
                    
                    jLabel3.setText(s_id);
                    jButton2.setVisible(false);
                    jButton1.setLocation(jButton2.getLocation());
                    jButton1.setVisible(true);
                    
                    
// TODO add your handling code here:
                } catch (SQLException ex) {
                    Logger.getLogger(order_internal.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                String str3="insert into order3(s_id) values("+s_id+")" ;
                Statement st1=con.createStatement();
                st1.executeUpdate(str3);
                try
                {
                    String str4="SELECT max(`order_no`) FROM `order3` ";
                    //Statement st=con.createStatement();
                    
                    ResultSet r=st.executeQuery(str4);
                    r.next();
                    jLabel5.setText(Long.toString(r.getLong(1)));
                }
                
                catch (SQLException ex) {
                    Logger.getLogger(order_internal.class.getName()).log(Level.SEVERE, null,ex);
                    
                }
                String str4="UPDATE `order1` SET `order_no`='"+jLabel5.getText()+"' WHERE order_no is null" ;
                Statement st2=con.createStatement();
                st2.executeUpdate(str4);
            } catch (SQLException ex) {
                Logger.getLogger(order_internal.class.getName()).log(Level.SEVERE, null, ex);
            }
            String str6="select sum(o_quantity) from order1 where order_no='"+jLabel5.getText()+"'";
            Statement st3=con.createStatement();
            ResultSet r=st3.executeQuery(str6);
            r.next();
            Long sum=r.getLong(1);
            String str5="insert into order2(order_no,o_quantity,date) values('"+jLabel5.getText()+"',"+sum+",'"+jLabel8.getText()+"')";
            Statement st4=con.createStatement();
            st4.executeUpdate(str5);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(order_internal.class.getName()).log(Level.SEVERE, null, ex);
        }
          jButton3.setEnabled(false);
          //jTable1.setEnabled(false);
          //jTable1.getComponentPopupMenu().setEnabled(false);
          //jTable1.remove(jPopupMenu1);
         // jPopupMenu1.setVisible(false);
           jTable1.setComponentPopupMenu(null);
          }
          
        }
        else
        {
            
            JOptionPane.showMessageDialog(rootPane, "Please select supplier name to confirm order.");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed
public static String[] a4;//=new String[count];
 public static Long[] a5;//=new int[count];
  public static String[] a6;//=new String[count];
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       jTable1.setComponentPopupMenu(jPopupMenu1);
        try {                                         
            // TODO add your handling code here:
            //new order_internal().setVisible(false);
            //new order().setVisible(true);
            // new order().model1.addRow(rowData);
            /* DefaultTableModel model1=new DefaultTableModel();
            new order().jTable1.setModel(model1);
            String[] col_list={"Product name","Brand","Quantity"};
            new order(). model1.setColumnIdentifiers(col_list);
            try
            {
            
            String str="select product_name,brand,o_quantity from order1_arbt";
            
            Statement st=con.createStatement();
            ResultSet re=st.executeQuery(str);
            
            while(re.next())
            {
            int col_count=col_list.length;
            Object[] new_row=new Object[col_count];
            for(int i=0;i<col_count;i++)
            {
            new_row[i]=re.getObject(i+1);
            }
            new order().model1.addRow(new_row);
            }
            
            
            }
            catch(Exception ex)
            {
            JOptionPane.showMessageDialog(rootPane, ex.toString());
            }*/
            /* try {
            String str="select count(*) from order1_arbt";
            Statement b=con.createStatement();

            ResultSet rs=b.executeQuery(str);
            rs.next();
            count=rs.getInt("count(*)");
            } catch (SQLException ex) {
            Logger.getLogger(order_internal.class.getName()).log(Level.SEVERE, null, ex);
            }*/
            // JOptionPane.showMessageDialog(rootPane, ""+count);
            //public static
             count=jTable1.getRowCount();
            String[] a1=new String[count];
            // public static
            Long[] a2=new Long[count];
            // public static
            String[] a3=new String[count];
            try {
                String str="select * from order1_arbt";
                Statement b=con.createStatement();
                
                ResultSet rs=b.executeQuery(str);
                int i=0;
                //ArrayList<Object> rowlist=new ArrayList<>();
                
                while(rs.next())
                {
                    // for(int i=0;i<rs.getMetaData().getColumnCount();i++)
                    // {
                    //JOptionPane.showMessageDialog(rootPane, ""+rs.getString("product_name"));
                    // rowlist.add(rs.getString("product_name"));
                    //rowlist.add(rs.getInt("o_quantity"));
                    //rowlist.add(rs.getString("brand")
                    a1[i]=rs.getString("product_name");
                    a2[i]=rs.getLong("o_quantity");
                    a3[i]=rs.getString("brand");
                    //JOptionPane.showMessageDialog(rootPane, ""+a1[i]);
                    i=i+1;
                    // JOptionPane.showMessageDialog(rootPane, ""+i);
                    // }
                }
                a4=new String[count];
                a5=new Long[count];
                a6=new String[count];
                for(int j=0;j<count;j++)
                {
                    a4[j]=a1[j];
                    a5[j]=a2[j];
                    a6[j]=a3[j];
                    //JOptionPane.showMessageDialog(rootPane, a4[j]);
                }
            } catch (SQLException ex) {
                Logger.getLogger(order_internal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            back();
            
            
            String st11="delete from order1_arbt";
            Statement c;
            
            c = con.createStatement();
            
            c.executeUpdate(st11);
            
            this.dispose();
//new order_internal().dispose();
            
            
//new  order_internal().dispatchEvent(new WindowEvent(new order_internal(),WindowEvent.WINDOW_CLOSING));
        } catch (SQLException ex) {
            Logger.getLogger(order_internal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
//JOptionPane.showMessageDialog(rootPane, opt);
        if(opt!=0)
{
        try {
         // TODO add your handling code here:
        int op= JOptionPane.showConfirmDialog(rootPane,"Do you want to cancel order ?", "Confirmation", JOptionPane.YES_NO_OPTION);
         if(op==0)
         {
         String str="delete from order1_arbt";
         Statement st=con.createStatement();
         st.executeUpdate(str);
         this.dispose();
         }
     } catch (SQLException ex) {
         Logger.getLogger(order_internal.class.getName()).log(Level.SEVERE, null, ex);
     }
}
else
{
    this.dispose();
}
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

     try {
         int row=jTable1.getSelectedRow();
         
         String str="delete from order1_arbt where product_name='"+model1.getValueAt(row,0)+"' and brand='"+model1.getValueAt(row,1)+"'";
         Statement st=con.createStatement();
         st.executeUpdate(str);
         model1.removeRow(row);
         
         
// TODO add your handling code here:
     } catch (SQLException ex) {
         Logger.getLogger(order_internal.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(order_internal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(order_internal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(order_internal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(order_internal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new order_internal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
